### ISSUE TITLE
Interface for settings

### ISSUE THREAD

**Issue by Thurion** [Thurion/EDSM-RSE-for-EDMC#1]
A tab in settings containing the following options needs to be implemented:

- As radiobuttons
    -  radius to search for "red" systems
        - 250
        - 500
        - 750
        - 1000
        - 2000
    -  update interval in jumps
        - 1 (every jump)
        - 3
        - 5
        - 7
- A checkbox whether to automatically copy the destination to the clipboard
- A link to this Github project
- A small text that mentions EDTS for the database

All of these settings need to be stored. A single entry should suffice with the right bit mask.

**Comment by Thurion** [comment]
And a label for the current version should also be on there.

**Comment by RapidfireCRH** [comment]
Bits 0 - 3: radius
000 - Custom range
001 - 100
010 - 250
011 - 500
100 - 750
101 - 1000
110 - 2000
111 - 4000

Bits 4-5: Update int
00 - 1
01 - 3
10 - 5
11 - 7

Bit 6: hijack clipboard

**Comment by Thurion** [comment]
Custom range? Where is the value for that stored?

**Comment by RapidfireCRH** [comment]
copyToClipboard - copy to clipboard toggle
radius - distance to search (is radius, not diamiter bubble)
updateInterval - how often it updates

VERSION - version number
db_date - NOT CREATED YET

**Comment by RapidfireCRH** [comment]
Ill hold off on the custom range till we get radio's working

**Comment by Thurion** [comment]
Implemented in commit fb22710d3d47646c449dfa0058b21677426eb9fc
