### ISSUE TITLE
Skipping entries button

### ISSUE THREAD

**Issue by ghost** [Thurion/EDSM-RSE-for-EDMC#11]
During the test drive in the bubble, I came across various "unconfirmed" systems that had been added to EDSM in Gamma/early 1.0 and were renamed or deleted from the game later.  See the trilateration needed room on the EDSM discord for examples.

Right now, such a system is a show-stopper because you cannot jump to it.  This leaves either

1. jumping around at random until you get another system
2. waiting until one of the EDSM admins has confirmed the name chang and updated EDSM
3. stopping EMDC, opening the DB with sqliteadmin, and deleting the system manually

There should be some kind of skip/ignore button in the UI that will remove the system from the local DB, and re-runs the search.

**Comment by RapidfireCRH** [comment]
Unfortunately Step 2 is the step we are looking for to resolve this issue. An ignore key would be hard to code into the display and still make it as low profile as it is now. Maybe including a "Rescan database" button in settings would allow you to remove the star, then have the add-in reload the database without having to close EDMC.

**Comment by Thurion** [comment]
Could be implemented with https://github.com/Thurion/EDSM-RSE-for-EDMC/issues/9 because it gives more room for stuff like that.

Possible approaches I can think of are
1. Hold ignored systems in memory for as long as EDMC runs.
2. Delete it from the local database.
3. Create a new file that holds the list of ignored systems. 
 
I think 1 or 2 is the best approach unless the user manually updates the local database every day.

**Comment by RapidfireCRH** [comment]
The ultimate goal of the plugin is to clean up these stars. "waiting until one of the EDSM admins has confirmed the name chang and updated EDSM" would be the preferred course of action. Second to that, deleting from the local database would be ok, until the next database update, which eventually should happen daily. I asked EDSM to provide some other avenue to peruse these changes but was told the current method (contact admins and wait) was the best method.

**Comment by gregmcdougall** [comment]
Suggestion - we already have the option to right-click a select 'copy'. can we have a further option for 'next' or similar? you'd re-run the query ignoring the currently suggested system. if it's too complex to hold 'ignored' systems can we simply remove them from the backend db as per RapidFire's suggestion (I do this manually at the moment if i'm static, but it's a little cumbersome) - rightclick 'delete'.

**Comment by Thurion** [comment]
I will look into the option to right click and ignore it. At least as long as the program is running. The database will move from a local database to an online one, so removing systems in the database is not an option.

**Comment by Thurion** [comment]
Added "ignore" to the context menu in current development branch (commit c9e226c). The list lives in memory and as long as you don't close EDMC, the system won't show up again.
I think this is an easy and convenient way to fix this issue. Therefore I consider it closed.
