### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by RapidfireCRH** [Thurion/EDSM-RSE-for-EDMC#31]
Thoughts on the new jobs coming through RSE:

Should the end user be able to choose which jobs they want to participate in?
Should we have the ability to turn off jobs at the server level?
How should someone submit for a new job to be added (google forums maybe)?

**Comment by victorleblais** [comment]
As a user, I would greatly appreciate to be able to filter/choose only specific types of jobs.

**Comment by Thurion** [comment]
Added with 20b4ff8
