### ISSUE TITLE
Copy system name on click

### ISSUE THREAD

**Issue by victorleblais** [Thurion/EDSM-RSE-for-EDMC#35]
Currently, clicking on the system name opens the EDSM page for it.

I'm aware you can turn on automatic copy into clipboard, but there are several reasons one might prefer not to have his clipboard changed automatically.

It would be great to have the option to "Click system name to copy it into clipboard".

If you still want the ability to open the EDSM page, you could display:

> Unconfirmed: Eol Prou Zo-U B18-28 (EDSM)

and add the ability to click on EDSM to open its page.

**Comment by Thurion** [comment]
The plugin uses the same behavior as EDMC itself:

- click to open link
- right click to get the option to either copy the name or ignore the system

**Comment by victorleblais** [comment]
I was unaware you could right-click the system name (either in your plugin or the base EDMC info). I'm sorry, this is perfectly fine then.

You can close this issue, I guess. :)
