### ISSUE TITLE
Scanned Systems Not Marked as 'Done'

### ISSUE THREAD

**Issue by gregmcdougall** [Thurion/EDSM-RSE-for-EDMC#38]
Had a couple previously offered (and scanned) systems come up today.

Didn't log all of them, but 'We Jenuteki' was definitely one of them. I ignored the first instance, and scanned 'We Jenuteki' again.

Can the delete on nav beacon scan be checked over? Happy to support testing if needed.

**Comment by RapidfireCRH** [comment]
How long ago did you scan? Your EDSM flight log isnt public though i do see the entries (not timestamps) for the system.

**Comment by gregmcdougall** [comment]
I scanned Gienah @ 09:28 IGT on 24/09/2018
I scanned HIP 52045 @ 09:43 IGT on 24/09/2018

**Comment by RapidfireCRH** [comment]
Are you still having the issue? we ran some fixes that same day...

**Comment by gregmcdougall** [comment]
I'm out of the bubble, will confirm when I re-enter.

**Comment by gregmcdougall** [comment]
This is still an issue for me. Herfjoturr beacon scanned, completed and offered new system. Closed EDMC, reopened. Jumped to neighbouring system. reoffered Herfjoturr again.

**Comment by RapidfireCRH** [comment]
completed are stored locally. Updates run every 24 hours. If you close out and reopen it would offer the same system since its not marked as complete yet on the server side

**Comment by RapidfireCRH** [comment]
Im not exactly sure when this is done, sometime in the morning CET i would assume
