### ISSUE TITLE
Handle duplicate system names

### ISSUE THREAD

**Issue by Thurion** [Thurion/EDSM-RSE-for-EDMC#4]
Duplicate system names are already in the database but need to be handled in the program.
`EliteSystem.getUncertainty() * 1.732051` can be use to calculate the worst case. If the distance from the current system to the duplicate system is smaller than the worst case it must be considered as overlapping and is therefore valid. Following cases need to be considered:
- Only one of the duplicates is valid: Delete it from the database
- More than one duplicate is valid: Ask the user to which system they jumped to. Remove the selected one from the database.

**Comment by RapidfireCRH** [comment]
Didn't you solve this by landing in all the duplicate systems?

**Comment by Thurion** [comment]
Yes and I think fdev renamed them. But I'm not sure. Anyway, we won't do anything about them.
