### ISSUE TITLE
EDSM hidden systems not being removed

### ISSUE THREAD

**Issue by klightspeed** [Thurion/EDSM-RSE-for-EDMC#42]
RSE does not appear to be removing hidden systems from its database.

> [12:23 PM] Xalder: RSE is telling me to scan the Navbeacon at Ravenhold... rather it specifically says "Unconfirmed: [New]Ravenhold ... Action: Scan navbeacon."
> [12:23 PM] Xalder: I'm at that system and have scanned the navbeacon but RSE hasn't changed. Not sure what else it wants.
> [12:29 PM] Xalder: Okay it's a game of triple links for the same system, starting with this one. https://www.edsm.net/en/system/id/22749414/name/%5BNew%5DRavenhold
> [12:29 PM] Xalder: RSE is telling me to go there, which moved to https://www.edsm.net/en/system/id/4427405/name/Eol+Prou+RS-T+d3-612 which moved to https://www.edsm.net/en/system/id/22982534/name/Ravenhold

Hidden systems can be retrieved from https://www.edsm.net/api-v1/hidden-systems?showid=1

**Comment by RapidfireCRH** [comment]
This should be fixed, let us know if it comes up again
