### ISSUE TITLE
cyberlord.de

### ISSUE THREAD

**Issue by gregmcdougall** [Thurion/EDSM-RSE-for-EDMC#43]
After having problems accessing the database online hosted on cyberlord.de it now appears that the site is running from two IP addresses. For me cyberlord.de resolves as follows:

Pinging cyberlord.de [213.120.234.109] with 32 bytes of data:

The script cannot connect to the database.

Altering the script to 185.80.92.171 resolves the issue and EDSM-RSE returns systems again.

Putting both 185.80.92.171 and cyberlord.de into a browser resolve to the same default Apache page.

**Comment by Thurion** [comment]
I informed the owner of the domain to look into this.

**Comment by Thurion** [comment]
We couldn't reproduce the problem. Make sure you reset your DNS cache. In Windows you can do this by running ``ipconfig /flushdns`` on a command line.

If the problem persists, please let us know.

**Comment by gregmcdougall** [comment]
It's back as an issue.

Script amended to point to IP address and issue solved.

Cyberlord.de now resolving to cyberlord.de [213.120.234.122] (note this is not the same as the first occurrence).

**Comment by RapidfireCRH** [comment]
IP of the server has not changed. What is changing your DNS entries? 185.80.92.171 has been the ip since you reported the issue

**Comment by gregmcdougall** [comment]
Could be a bad ISP, but I'm with a reputable provider. I'll look into it, and stick with the hardcoded IP for now. I'm not a DNS expert but I'll take a look and see how I get on.

**Comment by RapidfireCRH** [comment]
Cool, keep us in the loop. If your script suddenly stops running, message me on discord (RapidfireCRH#7694) and ill give you the new ip (if there is one)

**Comment by gregmcdougall** [comment]
i've put an entry in the hosts file for now. it's pretty obviously a problem with my ISP DNS. 

https://dnschecker.org/#A/cyberlord.de pretty much confirms that every public DNS server on the planet is resolving the entry correctly.

**Comment by Thurion** [comment]
You could configure your router or computer to use a free public DNS:
https://www.lifewire.com/free-and-public-dns-servers-2626062
