### ISSUE TITLE
Update mechanism for the database

### ISSUE THREAD

**Issue by Thurion** [Thurion/EDSM-RSE-for-EDMC#5]
A way to update the local database with the press of a button. A unix time stamp of when the database was created is stored in there an can be used to check if a newer version is available.

**Comment by RapidfireCRH** [comment]
dropbox allows you to store a text file. we could write a version text file to dropbox then if the dates are different, alert that new version is available. Download itself could also be handled through dropbox

**Comment by Thurion** [comment]
Google Drive could work too

**Comment by Thurion** [comment]
I found a python code snippet that claims to be able to download files from Google Drive:
https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive

**Comment by Thurion** [comment]
No longer needed because of the hosted database.
