### ISSUE TITLE
EDMC is moving to Python 3.7 'soon'

### ISSUE THREAD

**Issue by Athanasius** [Thurion/EDSM-RSE-for-EDMC#51]
I see you have a dual-python release dev branch.  You might want to look into making a release based on it sooner rather than later as it now won't be too long before latest EDMC release is based on Python 3.7.

**Comment by Thurion** [comment]
Thanks for letting me know.
I'm planning to release it this week after we tested it a bit more thoroughly. A few key components changed and I want to make sure it works.

**Comment by Athanasius** [comment]
Well, 3.46 of EDMC, which should be the final Python 2.7 release, was only picked up by some people today (the old update check interval was 47 hours, and it's now just over that since I properly published 3.46).

So it'll be at *least* another week before a Python 3.7 based release, and more likely longer than that.  I did put out a 3.51 pre-release that is bugfix/tweak synchronised with that 3.46.  Once I'm done fiddling with another project I'll start making sure README and Wiki stuff is all up to date and ready to go then have a better idea of when 4.00 (Python 3 plugin API change is breaking enough to require a major version bump) will be released.
