### ISSUE TITLE
give min and max range on distance

### ISSUE THREAD

**Issue by RapidfireCRH** [Thurion/EDSM-RSE-for-EDMC#6]
Cometborne - Today at 11:42 AM
One recommendation I have is to not give "the distance", but a range.
Basically, if you have the position from Alot's formulas and the uncertainty, you can calculate the 8 corners of the cube where the star should be
And then you can calculate the distances between the current position and those 8 corners, and report the minimum and maximum

**Comment by Thurion** [comment]
Why so complicated? We know the uncertainty on each axis. That multiplied by SQRT(3) gives the maximum distance. And it's already planned. See https://github.com/Thurion/EDSM-RSE-for-EDMC/issues/2
