### ISSUE TITLE
Six-Shooter here, I stopped with EDMC-repack

### ISSUE THREAD

**Issue by six-shooter** [Thurion/EDSM-RSE-for-EDMC#60]
The following line in your description is no longer true, I have stopped making it due to server and plugin changes.
The basic concept still works, so if you need any info on how I did it, ask me :)

"This plugin is part of the EDMC repack by Six-Shooter. You can download the repack at http://edfs.space/index.php/Tools"

**Comment by Thurion** [comment]
Thanks for letting me know. I updated the readme.
