### ISSUE TITLE
Suggestion to Add a Github Topic

### ISSUE THREAD

**Issue by dylan-k** [Thurion/EDSM-RSE-for-EDMC#61]
Github has a tags feature that I've found to be quite useful for finding [repos related to Elite Dangerous](https://github.com/topics/elite-dangerous). I noticed that this one might benefit from adding the `elite-dangerous` tag. Github calls them topics and says: To associate your repository with the elite-dangerous topic, visit your repo's landing page and select "manage topics." I'm very glad I found this fun app, and hope this would help others to do so as well.

**Comment by Thurion** [comment]
Thanks for letting me know. I added the topic as you suggested.

**Comment by dylan-k** [comment]
Looks good! Might be worthwhile for your other ED-related repos too?

**Comment by Thurion** [comment]
I did it for the other EDMC plugins. But there is no harm in adding the tag to the other ones, I suppose
