### ISSUE TITLE
Local cache database could not be opened

### ISSUE THREAD

**Issue by traveller42** [Thurion/EDSM-RSE-for-EDMC#63]
After updating I get the following error:

`EDSM-RSE-1.4: Local cache database could not be opened.`

How do I remedy this condition?

**Comment by Thurion** [comment]
Does it happen always after launching EDMC or just one time?

You could open the plugin directory and rename or delete the file `cache.sqlite`. Please do that while EDMC is not running.

One thing I can also think of is that EDMC didn't shut down completely the last time you used it and the database is still open. A reboot or killing the EDMC instance, that didn't shut down, through the task manager should do the trick in this case.

**Comment by Thurion** [comment]
Could you please check the log file (you can find out where to find it at https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#reporting-a-problem) as well?
There should be a line like `Exception in thread EDSM-RSE Background Worker` in there, followed by a stacktrace.

**Comment by traveller42** [comment]
Ultimate fix was to restore the `cache.sqlite` file from backup.

Proximate cause is renaming the old folder instead of removing it.  Since it did not end in .disabled, it was loaded and that likely ended up with a corrupted file.

Chalk it up to user error.  I did not find instructions for how to update the plugin.  I now know to just remove and replace.

Sorry to waste your time.

**Comment by Thurion** [comment]
>  I did not find instructions for how to update the plugin.

That's something I can improve by writing it in the readme and patch notes.
