### ISSUE TITLE
Overlay issue

### ISSUE THREAD

**Issue by CMDR-John-Romano** [Thurion/EDSM-RSE-for-EDMC#64]
I have the always on top box checked. while browsing internet, EDDN, EDSM ect it stays on top. However when in game; Elite Dangerous, it doesnt display over game. Ive tried uninstalling, reinstalling, disable setting and re-enabling overlay but still wont work. For a while it worked perfectly fine until I got online today. 

Is there is work around or is this a bug?

**Comment by CMDR-John-Romano** [comment]
never mind, I had the wrong option for display on in game. sorry!

**Comment by Thurion** [comment]
It would probably be an option for EDMC and not for this plug-in. But it seems you found it.

**Comment by HalJordan** [comment]
For anyone else, as I had this happen as well, I had to set the game to be below all others.
