### ISSUE TITLE
Ignore Once

### ISSUE THREAD

**Issue by gregmcdougall** [Thurion/EDSM-RSE-for-EDMC#66]
I would appreciate if one of the right-click actions was 'ignore once' so that i can pull up the next system after submitting a distance, but where i'd like that system re-presented on the next jump. currently i need to ignore this session, then restart.

**Comment by Thurion** [comment]
Added in c3a99d5. You can download the current development version https://github.com/Thurion/EDSM-RSE-for-EDMC/archive/refs/heads/development.zip and give it a go.

**Comment by gregmcdougall** [comment]
ignore once works, but seems to have broken 'ignore indefinitely' (haven't moved beyond the development release above)

**Comment by Thurion** [comment]
You're right. That was due to an oversight on my part.
There was also an issue with "ignore once" because I think it was ignored for 30-45 minutes before it showed up in the list again.

I pushed the fix onto the development branch.
